"""Data v3: 130 Bahasa & Regional Locales.

Sesuai permintaan pengguna:
- Bahasa daerah Indonesia HANYA bahasa Jawa (jv). Bahasa daerah lain (su, min, ban, ace, mad, bjn) dihapus.
- Daftar 130 bahasa/locale terstruktur dan transparan berdasarkan coverage tier:
  * curated: Bahasa utama dengan ratusan/ribuan kata terverifikasi.
  * regional: Varian wilayah/dialek dengan kata spesifik regional + inherit base.
  * starter: Korpus komunitas starter dengan kata-kata kasar esensial.
"""

# Daftar resmi 130 bahasa & regional locales (1–130)
LANGUAGES_130 = [
    (1, "Afrikaans", "af", "curated"),
    (2, "Albanian", "sq", "curated"),
    (3, "Amharic", "am", "curated"),
    (4, "Arabic", "ar", "curated"),
    (5, "Armenian", "hy", "curated"),
    (6, "Assamese", "as", "starter"),
    (7, "Azerbaijani", "az", "curated"),
    (8, "Basque", "eu", "curated"),
    (9, "Belarusian", "be", "curated"),
    (10, "Bengali", "bn", "curated"),
    (11, "Bosnian", "bs", "starter"),
    (12, "Breton", "br", "starter"),
    (13, "Bulgarian", "bg", "curated"),
    (14, "Burmese", "my", "curated"),
    (15, "Catalan", "ca", "curated"),
    (16, "Cebuano", "ceb", "curated"),
    (17, "Corsican", "co", "starter"),
    (18, "Croatian", "hr", "curated"),
    (19, "Czech", "cs", "curated"),
    (20, "Danish", "da", "curated"),
    (21, "Dutch", "nl", "curated"),
    (22, "Dutch (Belgium)", "nl-be", "regional"),
    (23, "English (UK)", "en-gb", "regional"),
    (24, "English (US)", "en-us", "curated"),
    (25, "English (Australia)", "en-au", "regional"),
    (26, "English (Canada)", "en-ca", "regional"),
    (27, "English (India)", "en-in", "regional"),
    (28, "English (Singapore)", "en-sg", "regional"),
    (29, "English (New Zealand)", "en-nz", "regional"),
    (30, "English (Ireland)", "en-ie", "regional"),
    (31, "English (South Africa)", "en-za", "regional"),
    (32, "Esperanto", "eo", "curated"),
    (33, "Estonian", "et", "curated"),
    (34, "Faroese", "fo", "starter"),
    (35, "Filipino", "fil", "curated"),
    (36, "Finnish", "fi", "curated"),
    (37, "French (Canada)", "fr-ca", "regional"),
    (38, "French (France)", "fr-fr", "curated"),
    (39, "Frisian", "fy", "starter"),
    (40, "Fula", "ff", "starter"),
    (41, "Galician", "gl", "curated"),
    (42, "Georgian", "ka", "starter"),
    (43, "German", "de", "curated"),
    (44, "Greek", "el", "curated"),
    (45, "Guarani", "gn", "starter"),
    (46, "Gujarati", "gu", "curated"),
    (47, "Haitian Creole", "ht", "starter"),
    (48, "Hausa", "ha", "starter"),
    (49, "Hebrew", "he", "starter"),
    (50, "Hindi", "hi", "curated"),
    (51, "Hungarian", "hu", "curated"),
    (52, "Icelandic", "is", "curated"),
    (53, "Indonesian", "id", "curated"),
    (54, "Irish", "ga", "starter"),
    (55, "Italian", "it", "curated"),
    (56, "Japanese", "ja", "curated"),
    (57, "Japanese (Kansai)", "ja-kansai", "regional"),
    (58, "Javanese", "jv", "starter"),
    (59, "Kannada", "kn", "curated"),
    (60, "Kazakh", "kk", "starter"),
    (61, "Khmer", "km", "curated"),
    (62, "Kinyarwanda", "rw", "starter"),
    (63, "Korean", "ko", "curated"),
    (64, "Kurdish (Kurmanji)", "ku", "starter"),
    (65, "Kurdish (Sorani)", "ckb", "starter"),
    (66, "Kyrgyz", "ky", "starter"),
    (67, "Lao", "lo", "starter"),
    (68, "Latvian", "lv", "curated"),
    (69, "Lithuanian", "lt", "curated"),
    (70, "Macedonian", "mk", "curated"),
    (71, "Malagasy", "mg", "starter"),
    (72, "Malay", "ms", "curated"),
    (73, "Malayalam", "ml", "curated"),
    (74, "Maltese", "mt", "curated"),
    (75, "Marathi", "mr", "curated"),
    (76, "Mongolian", "mn", "curated"),
    (77, "Nepali", "ne", "starter"),
    (78, "Norwegian (Bokmål)", "no", "curated"),
    (79, "Norwegian (Nynorsk)", "nn", "starter"),
    (80, "Odia", "or", "starter"),
    (81, "Pashto", "ps", "starter"),
    (82, "Persian", "fa", "curated"),
    (83, "Polish", "pl", "curated"),
    (84, "Portuguese (Brazil)", "pt-br", "regional"),
    (85, "Portuguese (Portugal)", "pt-pt", "curated"),
    (86, "Punjabi", "pa", "curated"),
    (87, "Romanian", "ro", "curated"),
    (88, "Russian", "ru", "curated"),
    (89, "Sardinian", "sc", "starter"),
    (90, "Serbian", "sr", "curated"),
    (91, "Shona", "sn", "starter"),
    (92, "Silesian", "szl", "starter"),
    (93, "Simplified Chinese (China)", "zh-cn", "curated"),
    (94, "Sinhala", "si", "starter"),
    (95, "Slovak", "sk", "curated"),
    (96, "Slovenian", "sl", "curated"),
    (97, "Somali", "so", "starter"),
    (98, "Spanish", "es", "curated"),
    (99, "Spanish (Spain)", "es-es", "regional"),
    (100, "Spanish (Latin America)", "es-419", "regional"),
    (101, "Spanish (Mexico)", "es-mx", "regional"),
    (102, "Swahili", "sw", "curated"),
    (103, "Swedish", "sv", "curated"),
    (104, "Syriac", "syr", "starter"),
    (105, "Tajik", "tg", "starter"),
    (106, "Tamazight", "zgh", "starter"),
    (107, "Tamil", "ta", "curated"),
    (108, "Tatar", "tt", "starter"),
    (109, "Telugu", "te", "curated"),
    (110, "Tetun", "tet", "curated"),
    (111, "Thai", "th", "curated"),
    (112, "Traditional Chinese (Hong Kong)", "zh-hk", "regional"),
    (113, "Traditional Chinese (Taiwan)", "zh-tw", "regional"),
    (114, "Turkish", "tr", "curated"),
    (115, "Ukrainian", "uk", "curated"),
    (116, "Urdu", "ur", "curated"),
    (117, "Uzbek", "uz", "curated"),
    (118, "Vietnamese", "vi", "curated"),
    (119, "Welsh", "cy", "curated"),
    (120, "Zaza", "zza", "starter"),
    (121, "Ainu", "ain", "starter"),
    (122, "Akan", "ak", "starter"),
    (123, "Aragonese", "an", "starter"),
    (124, "Aymara", "ay", "starter"),
    (125, "Balochi", "bal", "starter"),
    (126, "Bambara", "bm", "starter"),
    (127, "Bhojpuri", "bho", "starter"),
    (128, "Dzongkha", "dz", "curated"),
    (129, "Igbo", "ig", "starter"),
    (130, "Yoruba", "yo", "starter"),
]

# Korpus tambahan & regional untuk bahasa yang tidak ada di upstream safe_text
EXTRA_LANGS = {
    # 58. Javanese (Satu-satunya bahasa daerah Indonesia)
    "jv": {
        "name": "Javanese",
        "maturity": "starter",
        "source": "curated javanese wordlist",
        "words": [
            "jancok", "cuk", "asu", "bajingan", "matamu", "gendeng", "edan",
            "koen", "ndhasmu", "cuki", "gatheli", "celeng", "cangkemmu",
            "picek", "kampret", "kontol", "tempik", "jembut", "kirik", "babi", "jancuk"
        ],
    },
    # Regional dialects
    "nl-be": {
        "name": "Dutch (Belgium)",
        "maturity": "regional",
        "source": "flemish regional vocabulary",
        "parent": "nl",
        "words": ["kloothakkel", "schijterd", "strontzak", "krapuul", "smoutbol"],
    },
    "en-gb": {
        "name": "English (UK)",
        "maturity": "regional",
        "source": "british english regional slurs",
        "parent": "en-us",
        "words": ["wanker", "bollocks", "twat", "tosser", "minger", "bellend", "slag", "pillock", "chav"],
    },
    "en-au": {
        "name": "English (Australia)",
        "maturity": "regional",
        "source": "australian english regional slurs",
        "parent": "en-us",
        "words": ["bogan", "drongo", "wanker", "galah", "dipstick", "cunt"],
    },
    "en-ca": {
        "name": "English (Canada)",
        "maturity": "regional",
        "source": "canadian english regional slurs",
        "parent": "en-us",
        "words": ["hoser", "skid", "douchebag", "shithead"],
    },
    "en-in": {
        "name": "English (India)",
        "maturity": "regional",
        "source": "indian english slang/slurs",
        "parent": "en-us",
        "words": ["chutiya", "bhenchod", "madarchod", "gandu", "harami", "bastard"],
    },
    "en-sg": {
        "name": "English (Singapore)",
        "maturity": "regional",
        "source": "singlish profanities",
        "parent": "en-us",
        "words": ["cheebai", "cb", "lanjiao", "kanina", "pukimak", "bodoh", "siao"],
    },
    "en-nz": {
        "name": "English (New Zealand)",
        "maturity": "regional",
        "source": "nz english slurs",
        "parent": "en-us",
        "words": ["bogan", "wanker", "dickhead", "scumbag"],
    },
    "en-ie": {
        "name": "English (Ireland)",
        "maturity": "regional",
        "source": "irish english slurs",
        "parent": "en-us",
        "words": ["feck", "gobshite", "shite", "eejit", "arsehole", "wanker"],
    },
    "en-za": {
        "name": "English (South Africa)",
        "maturity": "regional",
        "source": "south african english slurs",
        "parent": "en-us",
        "words": ["poes", "kak", "doos", "naaier", "bliksem", "fokof", "voetsek"],
    },
    "fr-ca": {
        "name": "French (Canada)",
        "maturity": "regional",
        "source": "quebecois profanities (sacres)",
        "parent": "fr-fr",
        "words": ["tabarnak", "calisse", "ostie", "criss", "ciboire", "marde", "viarge", "simonaque"],
    },
    "ja-kansai": {
        "name": "Japanese (Kansai)",
        "maturity": "regional",
        "source": "kansai dialect insults",
        "parent": "ja",
        "words": ["aho", "kasu", "bokey", "dabo", "tare"],
    },
    "pt-br": {
        "name": "Portuguese (Brazil)",
        "maturity": "regional",
        "source": "brazilian portuguese slurs",
        "parent": "pt-pt",
        "words": ["porra", "caralho", "filho da puta", "merda", "vai tomar no cu", "viado", "arrombado", "bosta"],
    },
    "zh-hk": {
        "name": "Traditional Chinese (Hong Kong)",
        "maturity": "regional",
        "source": "cantonese profanities",
        "parent": "zh-cn",
        "words": ["仆街", "撚", "鳩", "柒", "頂你個肺", "冚家剷", "老母", "臭閪", "閪"],
    },
    "zh-tw": {
        "name": "Traditional Chinese (Taiwan)",
        "maturity": "regional",
        "source": "taiwanese profanities",
        "parent": "zh-cn",
        "words": ["幹", "三小", "靠北", "靠夭", "機掰", "王八蛋", "白癡", "操你媽", "智障"],
    },
    "es-es": {
        "name": "Spanish (Spain)",
        "maturity": "regional",
        "source": "castilian spanish slurs",
        "parent": "es",
        "words": ["gilipollas", "coño", "joder", "hostia", "cabrón", "capullo", "hijo de puta"],
    },
    "es-419": {
        "name": "Spanish (Latin America)",
        "maturity": "regional",
        "source": "latin american spanish slurs",
        "parent": "es",
        "words": ["pelotudo", "boludo", "concha de tu madre", "chucha", "huevón", "malparido", "gonorrea"],
    },
    "es-mx": {
        "name": "Spanish (Mexico)",
        "maturity": "regional",
        "source": "mexican spanish slurs",
        "parent": "es",
        "words": ["chingar", "pinche", "pendejo", "cabrón", "chingada", "verga", "culero", "mamón", "wey"],
    },
    "nn": {
        "name": "Norwegian (Nynorsk)",
        "maturity": "starter",
        "source": "nynorsk profanities",
        "parent": "no",
        "words": ["faen", "helvete", "jævla", "dritt", "satans", "fitte", "kjerring"],
    },
    # Bahasa baru dari daftar 130
    "as": {"name": "Assamese", "maturity": "starter", "source": "assamese starter list", "words": ["kela", "baal", "sodam", "magi", "khanki", "bapere"]},
    "bs": {"name": "Bosnian", "maturity": "starter", "source": "bosnian starter list", "words": ["kurac", "picka", "jebem", "govno", "govnar", "pizda", "supak"]},
    "br": {"name": "Breton", "maturity": "starter", "source": "breton starter list", "words": ["gast", "kaoc'h", "penn-lost", "revr", "bouc'h"]},
    "co": {"name": "Corsican", "maturity": "starter", "source": "corsican starter list", "words": ["merda", "cazzu", "stronzu", "puttana", "bastardu"]},
    "fo": {"name": "Faroese", "maturity": "starter", "source": "faroese starter list", "words": ["skit", "helvíti", "lort", "rannsakari", "fari"]},
    "fy": {"name": "Frisian", "maturity": "starter", "source": "frisian starter list", "words": ["klote", "sukkel", "lul", "kanker", "ferdomme"]},
    "ff": {"name": "Fula", "maturity": "starter", "source": "fula starter list", "words": ["sofa", "bonki", "gorko", "nyande", "mbeelu"]},
    "ka": {"name": "Georgian", "maturity": "starter", "source": "georgian starter list", "words": ["dzagli", "shekhebi", "motyvnuli", "nagavi"]},
    "gn": {"name": "Guarani", "maturity": "starter", "source": "guarani starter list", "words": ["tavy", "jagua", "vyro", "tevi"]},
    "ht": {"name": "Haitian Creole", "maturity": "starter", "source": "haitian creole starter list", "words": ["koko", "boudin", "zozo", "kaka", "salop", "madichon"]},
    "ha": {"name": "Hausa", "maturity": "starter", "source": "hausa starter list", "words": ["dan banza", "dan iska", "wawa", "uwarka", "sakara"]},
    "he": {"name": "Hebrew", "maturity": "starter", "source": "hebrew starter list", "words": ["ben zona", "kus emek", "lech tizdayen", "sharmuta", "tizdayen", "dafa"]},
    "ga": {"name": "Irish", "maturity": "starter", "source": "irish starter list", "words": ["amadan", "cac", "bastaird", "pleidhce", "diabhal"]},
    "kk": {"name": "Kazakh", "maturity": "starter", "source": "kazakh starter list", "words": ["it", "akymak", "mal", "suka", "kotoq"]},
    "rw": {"name": "Kinyarwanda", "maturity": "starter", "source": "kinyarwanda starter list", "words": ["imbwa", "igipupa", "umusazi", "ikigoryi"]},
    "ku": {"name": "Kurdish (Kurmanji)", "maturity": "starter", "source": "kurdish kurmanji starter list", "words": ["se", "ker", "gej", "beaqil", "quz"]},
    "ckb": {"name": "Kurdish (Sorani)", "maturity": "starter", "source": "kurdish sorani starter list", "words": ["gahba", "qon", "kiri", "xar", "daik"]},
    "ky": {"name": "Kyrgyz", "maturity": "starter", "source": "kyrgyz starter list", "words": ["it", "akmak", "eshek", "topos"]},
    "lo": {"name": "Lao", "maturity": "starter", "source": "lao starter list", "words": ["ba", "khuay", "ma", "satin", "i-hee"]},
    "mg": {"name": "Malagasy", "maturity": "starter", "source": "malagasy starter list", "words": ["alika", "adala", "voretra", "amany"]},
    "ne": {"name": "Nepali", "maturity": "starter", "source": "nepali starter list", "words": ["muji", "randi", "gadha", "kutta", "bhosdike", "lado"]},
    "or": {"name": "Odia", "maturity": "starter", "source": "odia starter list", "words": ["gandi", "madarchod", "bhenchod", "sala", "maghia"]},
    "ps": {"name": "Pashto", "maturity": "starter", "source": "pashto starter list", "words": ["spay", "harami", "lewanay", "dagha", "kosem"]},
    "sc": {"name": "Sardinian", "maturity": "starter", "source": "sardinian starter list", "words": ["merda", "caddhos", "putana", "cazzu", "marranu"]},
    "sn": {"name": "Shona", "maturity": "starter", "source": "shona starter list", "words": ["imbwa", "benzi", "mhata", "rombe", "mupengo"]},
    "szl": {"name": "Silesian", "maturity": "starter", "source": "silesian starter list", "words": ["pizda", "chuj", "kurwa", "kupa", "dupcyc"]},
    "si": {"name": "Sinhala", "maturity": "starter", "source": "sinhala starter list", "words": ["balla", "huththa", "kariya", "paka", "ponnaya"]},
    "so": {"name": "Somali", "maturity": "starter", "source": "somali starter list", "words": ["doqon", "walan", "nacas", "dameer", "futo"]},
    "syr": {"name": "Syriac", "maturity": "starter", "source": "syriac starter list", "words": ["khara", "sharmuta", "kalba", "kesha"]},
    "tg": {"name": "Tajik", "maturity": "starter", "source": "tajik starter list", "words": ["sag", "ahmak", "har", "khar", "kuni"]},
    "zgh": {"name": "Tamazight", "maturity": "starter", "source": "tamazight starter list", "words": ["aqlab", "qaz", "amxix", "tayri"]},
    "tt": {"name": "Tatar", "maturity": "starter", "source": "tatar starter list", "words": ["kүt", "suk", "blyad", "sikem", "harna"]},
    "zza": {"name": "Zaza", "maturity": "starter", "source": "zaza starter list", "words": ["guro", "kutik", "koli", "qun", "her"]},
    "ain": {"name": "Ainu", "maturity": "starter", "source": "ainu starter list", "words": ["wenkamuy", "taskur", "sirpiri", "ray"]},
    "ak": {"name": "Akan", "maturity": "starter", "source": "akan starter list", "words": ["kwasia", "gyimii", "aboa", "twe", "kote"]},
    "an": {"name": "Aragonese", "maturity": "starter", "source": "aragonese starter list", "words": ["mierda", "cojon", "puta", "capullo", "esconjurau"]},
    "ay": {"name": "Aymara", "maturity": "starter", "source": "aymara starter list", "words": ["mierda", "carajo", "jodido"]},
    "bal": {"name": "Balochi", "maturity": "starter", "source": "balochi starter list", "words": ["madarsag", "harami", "gand", "kuss", "zanag"]},
    "bm": {"name": "Bambara", "maturity": "starter", "source": "bambara starter list", "words": ["furu", "naman", "bo", "dunan", "nsono"]},
    "bho": {"name": "Bhojpuri", "maturity": "starter", "source": "bhojpuri starter list", "words": ["bhosadike", "chutiya", "bhenchod", "madarchod", "gandu", "raand"]},
    "ig": {"name": "Igbo", "maturity": "starter", "source": "igbo starter list", "words": ["nzuzu", "onye ara", "efulefu", "anumanu", "ewu"]},
    "yo": {"name": "Yoruba", "maturity": "starter", "source": "yoruba starter list", "words": ["oloshi", "omo ale", "olori buruku", "were", "ode", "asinwin"]},
}

# Regional overrides
REGIONS = {
    "ID": {"note": "anak yatim = 'orphan', terlalu luas untuk di-flag",
           "source": "kurasi lokal — presisi",
           "add": [],
           "remove": [{"w": "anak yatim", "lang": "id"}]},
    "NO": {"note": "fart = 'speed' (netral) dalam bahasa Norwegia",
           "source": "kamus umum — butuh verifikasi native",
           "add": [],
           "remove": [{"w": "fart", "lang": "no"}]},
    "DK": {"note": "fart = 'speed' (netral) dalam bahasa Denmark",
           "source": "kamus umum — butuh verifikasi native",
           "add": [],
           "remove": [{"w": "fart", "lang": "da"}]},
    "SE": {"note": "fart = 'speed' (netral) dalam bahasa Swedia",
           "source": "kamus umum — butuh verifikasi native",
           "add": [],
           "remove": [{"w": "fart", "lang": "sv"}]},
    "AU": {"note": "thumbs-up gesture dianggap kasar; lihat emoji map",
           "source": "etiket perjalanan umum — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "IR": {"note": "thumbs-up gesture dianggap kasar; lihat emoji map",
           "source": "etiket perjalanan umum — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "AF": {"note": "thumbs-up gesture dianggap kasar; lihat emoji map",
           "source": "etiket perjalanan umum — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "CN": {"note": "angka 4 dihindari (tetraphobia); lihat emoji/simbol",
           "source": "pengetahuan umum budaya — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "JP": {"note": "angka 4 dihindari (tetraphobia)",
           "source": "pengetahuan umum budaya — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "KR": {"note": "angka 4 dihindari (tetraphobia)",
           "source": "pengetahuan umum budaya — verifikasi lokal disarankan",
           "add": [], "remove": []},
}

# Emoji map
EMOJI = {
    "\U0001F595": {"offensiveIn": ["*"], "severity": 3,
                   "note": "middle finger — offensif universal",
                   "source": "general knowledge"},
    "\U0001F44D": {"offensiveIn": ["IR", "AF", "AU"], "severity": 2,
                   "note": "thumbs-up dianggap kasar di sebagian Timur Tengah & Australia",
                   "source": "travel etiquette guides — verify locally"},
}

# Curated categories
CURATED_CATEGORIES = [
    ("id", "anjing", "kasar"), ("id", "bangsat", "kasar"), ("id", "bajingan", "kasar"),
    ("id", "kontol", "sexual"), ("id", "memek", "sexual"), ("id", "ngentot", "sexual"),
    ("id", "goblok", "kasar"), ("id", "tolol", "kasar"), ("id", "idiot", "kasar"),
    ("id", "kafir", "sara"), ("id", "bunuh", "violence"), ("id", "bacok", "violence"),
    ("jv", "jancok", "kasar"), ("jv", "asu", "kasar"), ("jv", "bajingan", "kasar"),
    ("jv", "kontol", "sexual"), ("jv", "tempik", "sexual"),
    ("en-us", "fuck", "sexual"), ("en-us", "shit", "sexual"), ("en-us", "bitch", "sexual"),
    ("en-us", "dick", "sexual"), ("en-us", "bastard", "kasar"), ("en-us", "asshole", "kasar"),
    ("en-us", "nigger", "sara"), ("en-us", "kill", "violence"),
]

# Severity overrides
SEVERITY_OVERRIDES = [
    ("en-us", "nigger", 3), ("en-us", "chink", 3), ("en-us", "kike", 3), ("en-us", "faggot", 3),
]
