"""Data v3: 43 bahasa tambahan + regional overrides + emoji map + severity.

Maturity: 'draft' = daftar awal, WAJIB review native speaker (lihat source).
'seed-loanwords' = hanya loanword yang umum dipakai, belum ada daftar native.
Kontribusi/perbaikan via docs/CONTRIBUTING-langs.md
"""

EXTRA_LANGS = {
    "he": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["ben zona", "kus emek", "lech tizdayen", "sharmuta", "tizdayen", "dafa"]},
    "jv": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["jancok", "cuk", "asu", "bajingan", "matamu", "gendeng", "edan", "koen", "ndhasmu", "cuki"]},
    "su": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["anjir", "sia", "belegug", "koplok", "edan", "sialan", "goblok", "anjing"]},
    "min": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["pantek", "celako", "sial", "bajingan", "jamban"]},
    "ban": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["cicing", "celeng", "buduh", "jengah"]},
    "ace": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["asei", "bui", "bangai", "jalang"]},
    "mad": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["anjing", "bangsat", "gila", "sial", "jahanam"]},
    "bjn": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["bangsat", "anjing", "sial", "pantat", "wanyi"]},
    "ha": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["dan banza", "dan iska", "wawa", "uwarka", "sakara"]},
    "yo": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["oloshi", "omo ale", "olori buruku", "were", "ode", "asinwin"]},
    "ig": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["nzuzu", "onye ara", "efulefu", "anumanu", "ewu"]},
    "so": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["doqon", "walan", "nacas", "dameer", "futo"]},
    "ti": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["ahmak", "sheytan", "kefu"]},
    "om": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["eebba", "gudda", "arraba"]},
    "rw": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["imbwa", "igipupa", "umusazi", "ikigoryi"]},
    "sn": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["imbwa", "benzi", "mhata", "rombe"]},
    "xh": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["inja", "isidenge", "gqwirha", "sile"]},
    "ny": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["galu", "chitsiru", "mbuzi", "usilu"]},
    "mg": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["alika", "adala", "voretra"]},
    "ne": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["muji", "randi", "gadha", "kutta", "bhosdike"]},
    "si": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["balla", "huththa", "kariya", "paka"]},
    "lo": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["ba", "khuay", "ma", "satin"]},
    "ka": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["dzagli", "shekhebi", "motyvnuli"]},
    "kk": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["it", "akymak", "mal", "suka"]},
    "ky": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["it", "akmak", "eshek", "topos"]},
    "tg": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["sag", "ahmak", "har", "khar"]},
    "tk": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["it", "akmak", "eshek", "samsyk"]},
    "ps": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["spay", "harami", "lewanay", "dagha"]},
    "ku": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["se", "ker", "gej", "beaqil"]},
    "ga": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["amadan", "cac", "bastaird", "pleidhce"]},
    "fy": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["klote", "sukkel", "lul", "kanker"]},
    "lb": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["depp", "scheiss", "hueso"]},
    "bs": {"maturity": "draft", "source": "initial draft — needs native review (serbo-croatian cluster)",
           "words": ["kurac", "picka", "jebem", "govno", "govnar", "pizda"]},
    "haw": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["pupule", "hewa", "naaupo"]},
    "fj": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["lialia", "kuli", "vuce"]},
    "qu": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["asnu", "supay", "qhella"]},
    "gn": {"maturity": "draft", "source": "initial draft — needs native review",
           "words": ["tavy", "jagua", "vyro"]},
    "war": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["yawa", "buang", "tarantado"]},
    "hil": {"maturity": "draft", "source": "initial draft — needs native review",
            "words": ["yawa", "buang", "gago", "tarantado"]},
    # Ultra-low-confidence: hanya loanword yang umum dipakai + flag jelas.
    "dv": {"maturity": "seed-loanwords", "source": "english loans only — needs native (Dhivehi) list",
           "words": ["fuck", "shit"]},
    "chr": {"maturity": "seed-loanwords", "source": "english loans only — needs native (Cherokee) list",
            "words": ["fuck", "shit", "bitch"]},
    "kl": {"maturity": "seed-loanwords", "source": "danish/english loans only — needs native (Greenlandic) list",
           "words": ["fuck", "lort", "idiot"]},
    "ay": {"maturity": "seed-loanwords", "source": "spanish loans only — needs native (Aymara) list",
           "words": ["mierda", "carajo", "jodido"]},
}

# Regional overrides: add/remove per ISO country code.
# Script memvalidasi remove terhadap data base dan membuang yang tak cocok.
REGIONS = {
    "ID": {"note": "anak yatim = 'orphan', terlalu luas untuk di-flag",
           "source": "kurasi lokal — presisi",
           "add": [],
           "remove": [{"w": "anak yatim", "lang": "id"}]},
    "NO": {"note": "fart = 'speed' (netral) dalam bahasa Norwegia",
           "source": "kamus umum — butuh verifikasi native",
           "add": [],
           "remove": [{"w": "fart", "lang": "no"}]},
    "DK": {"note": "fart = 'speed' (netral) dalam bahasa Denmark",
           "source": "kamus umum — butuh verifikasi native",
           "add": [],
           "remove": [{"w": "fart", "lang": "da"}]},
    "SE": {"note": "fart = 'speed' (netral) dalam bahasa Swedia",
           "source": "kamus umum — butuh verifikasi native",
           "add": [],
           "remove": [{"w": "fart", "lang": "sv"}]},
    "AU": {"note": "thumbs-up gesture dianggap kasar; lihat emoji map",
           "source": "etiket perjalanan umum — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "IR": {"note": "thumbs-up gesture dianggap kasar; lihat emoji map",
           "source": "etiket perjalanan umum — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "AF": {"note": "thumbs-up gesture dianggap kasar; lihat emoji map",
           "source": "etiket perjalanan umum — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "CN": {"note": "angka 4 dihindari (tetraphobia); lihat emoji/simbol",
           "source": "pengetahuan umum budaya — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "JP": {"note": "angka 4 dihindari (tetraphobia)",
           "source": "pengetahuan umum budaya — verifikasi lokal disarankan",
           "add": [], "remove": []},
    "KR": {"note": "angka 4 dihindari (tetraphobia)",
           "source": "pengetahuan umum budaya — verifikasi lokal disarankan",
           "add": [], "remove": []},
}

# Emoji/gesture map. offensiveIn: ["*"] = universal, atau daftar country code.
EMOJI = {
    "\U0001F595": {"offensiveIn": ["*"], "severity": 3,
                   "note": "middle finger — offensif universal",
                   "source": "general knowledge"},
    "\U0001F44D": {"offensiveIn": ["IR", "AF", "AU"], "severity": 2,
                   "note": "thumbs-up dianggap kasar di sebagian Timur Tengah & Australia",
                   "source": "travel etiquette guides — verify locally"},
}

# Kategori kurasi lokal (diterapkan bila entri ada di data base).
CURATED_CATEGORIES = [
    ("id", "anjing", "kasar"), ("id", "bangsat", "kasar"), ("id", "bajingan", "kasar"),
    ("id", "kontol", "sexual"), ("id", "memek", "sexual"), ("id", "ngentot", "sexual"),
    ("id", "goblok", "kasar"), ("id", "tolol", "kasar"), ("id", "idiot", "kasar"),
    ("id", "kafir", "sara"), ("id", "bunuh", "violence"), ("id", "bacok", "violence"),
    ("en", "fuck", "sexual"), ("en", "shit", "sexual"), ("en", "bitch", "sexual"),
    ("en", "dick", "sexual"), ("en", "bastard", "kasar"), ("en", "asshole", "kasar"),
    ("en", "nigger", "sara"), ("en", "kill", "violence"),
]

# Severity 3 = slur berat. Diterapkan bila entri ada di data base.
SEVERITY_OVERRIDES = [
    ("en", "nigger", 3), ("en", "chink", 3), ("en", "kike", 3), ("en", "faggot", 3),
]
